###############################################################################
# NGINX & CERTBOT docker containers
###############################################################################

version: '3.9'

services:
  ##### nginx #####
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      # APP_URL: ${APP_URL:-school.inspire.hk}
      # S3_URL: ${APP_URL:-school.inspire.hk}
      # DOCKER_HOST: ${DOCKER_HOST:-192.168.40.20}
      APP_URL: ${APP_URL:-school.dev}
      API_HOST: ${DOCKER_HOST:-localhost}
    volumes:
      - ./conf/nginx/templates:/etc/nginx/templates
      # - ./conf/nginx/snippets:/etc/nginx/conf.d/snippets:ro
      - ./conf/www:/var/www:ro
      - ./data/certbot:/etc/letsencrypt:ro

  # #### certbot #####
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./conf/www/certbot:/var/www/certbot:rw
      - ./data/certbot:/etc/letsencrypt:rw
